apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-world
        image: registry.cn-hangzhou.aliyuncs.com/wxssaa/hello-world:0.0.2
        ports:
        - containerPort: 8888
